#Плагин создан Limon_MineDel
#LSRVDiscordNews - 1.0
#/fakenews - lsrvdn.fake - Отправить фейковое уведомление
#/latnews - lsrvdn.lat - получить ссылку на последнию новость
bot: #Настройки бота
  token: '103982451fdshsh88452qjdgfsdt' #Токен бота
  channel: 'idchannel' #ID Канала новостей
news: #Уведомление о новой новосте
  - '&d&lНОВАЯ НОВОСТЬ В DISCORD'
  - '&a&lНаш &d&lDISCORD&f: discord.gg/test'
  - '&a&lНовость можно посмотреть написав команду&f: /latnews'
  - '&d&lНОВАЯ НОВОСТЬ В DISCORD'
lang: #Языковые настройки
  noperm: '&c&lУ вас нет прав!' #Сообщение если нету прав
  last-post: #Языковые настройки для последней новости
    last: '&e&lСсылка на последнию новость&f:' #Сообщение если есть последняя новость, то даёт ссылку
    nolast: '&c&lНет недавних новостей' #Сообщение если нету последних новостей